---
title: "crossvariogram_landing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{crossvariogram_landing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The cross variogram is used in cokriging, which uses multiple variables in the spatial interpolation model. The cross variogram is defined as

$$
\gamma(t) = \frac 1 2 \mathrm{Cov}(X_t - X_0, Y_t - Y_0),
$$

where $Y$ is another variable. The cross variogram also has nugget, sill, and range. It shows how the covariance between two variables changes with distance. `Voyager` supports multiple bivariate spatial methods, and the cross variogram is one of them. 

Below is a list of vignettes that use the cross variogram. The links point to the sections that use the cross variogram. The corresponding Google Colab notebooks are also linked to. The list is sorted by technology.

| Vignette | Colab Notebook | Description |
|--------------------|:---------------:|---------------------------------|
| [Variogram demo](https://pachterlab.github.io/voyager/articles/variogram.html#cross-variogram) | [Colab Notebook](https://colab.research.google.com/github/pachterlab/voyager/blob/documentation-devel/vignettes/variogram.ipynb) | Demonstrate variograms on melanoma metastasis Slide-seq data
