---
title: "Pros and cons of spatial technologies"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pros_cons}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page lists the pros and cons of spatial technologies whose data is used on this website. This page focuses on the data, rather than the cost (usually not posted on the website) and ease of use by experimentalists who generate the data.

## Visium
Pros:

* Commercial kit
* Provided by many core facilities
* More widely available than most other spatial transcriptomics technologies
* Transcriptome wide
* FFPE compatible
* Can have a panel of proteins in addition to RNA
* Accompanied by H&E or fluorescent images for tissue morphology
* Because of the lower resolution, the data size is more manageable for larger tissue areas and larger number of samples

Cons:

* Lower resolution -- 55 $\mu$m spot diameter and 100 $\mu$m center to center
* Relatively low detection efficiency of transcripts
* Not full length, but protocol has been adapted for full length sequencing

## Slide-seq
Pros:

* Higher resolution than Visium, as the beads are 10 $\mu$m in diameter
* Transcriptome wide
* Recently commercialized as Curio, so there should be a commercial kit

Cons:

* Still not single cell resolution as two cells can occupy the same bead
* Relatively low detection efficiency of transcripts
* Existing datasets may not come with histology image

## MERFISH, CosMX, Xenium
Pros:

* Commercial kit
* Single cell resolution
* High detection efficiency
* FFPE compatible
* Get subcellular transcript localization information
* Can also get histological staining, at least DAPI
* Up to 100 proteins can be quantified with CosMX along side RNAs, though protein detection does not yet seen to be commercialized for MERFISH and Xenium

Cons:

* Need to pre-select a panel of usually a few hundred genes. However, the companies provide curated gene panels for common applications such as oncology, neuroscience, and immunology, as well as panel design services.
* Data size is harder to manage for larger tissue areas and number of samples. Not all spatial analysis methods can scale to hundreds of thousands to millions of cells.

## SeqFISH
Pros:

* Single cell resolution
* High detection efficiency
* Get subcellular transcript localization information
* Can also get histological staining, at least DAPI

Cons:

* No commercial kit yet
* Need to pre-select a panel of usually a few hundred genes

## CODEX
Pros:

* Commercial kit
* Single cell resolution
* FFPE compatible

Cons:

* Need panels of proteins usually with a few dozens of antibodies, but this is standard for highly multiplexed imunofluorescence. Akoya sells curated panels.
