---
title: "seqFISH Processing Workflows with Voyager"
output: html_document
vignette: >
  %\VignetteIndexEntry{seqfish_landing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

The seqFISH technology enables in situ profiling of individual molecules such as RNA, DNA, and protein via sequential rounds of fluorescent labeling and imaging ([Lubeck, et. al.](https://doi.org/10.1038/nmeth.2892)). The sequential labeling and imaging rounds can identify up to 24,000 unique targets, and recent publications have demonstrated the ability of the technology to robustly detect 10,000 genes in individual cells ([Eng, et. al.](https://doi.org/10.1038/s41586-019-1049-y)). To date, seqFISH has been applied to a number of tissue and organisms, including [brain](https://doi.org/10.1038/nbt.4260), [mouse embryo](https://doi.org/10.1038/s41587-021-01006-2), and [zebrafish embryo](https://doi.org/10.1038/s41467-021-23834-1).

## Analysis Workflows

The analysis tasks include basic quality control, spatial exploratory data analysis, identification of spatially variable genes, and computation of global and local spatial statistics. Accompanying Colab notebooks are linked when available.

| Vignette          |   Colab Notebook   | Description                   |
|-------------------|:------------------:|-------------------------------|
| [seqFISH exploratory data analysis](https://pachterlab.github.io/voyager/articles/vig7_seqfish.html) | | Perform basic QC, data normalization, dimension reduction, clustering, univariate spatial statistics, significance testing |
