---
title: "Chromium nuclei isolation basic quality control"
author: "Kayla Jackson and A. Sina Booeshaghi"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: true
  toc_float:
    collapsed: false
  toc_depth: 3
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
bibliography: ref.bib
vignette: >
  %\VignetteIndexEntry{10xnuclei_qc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", fig.align = "center"
)
```

```{r, include = FALSE, eval = FALSE}
# Install Google Colab dependencies
# Note: this can take 30+ minutes (many of the dependencies include C++ code, which needs to be compiled)

# First install `sf`, `ragg` and `textshaping` and their system dependencies:
system("apt-get -y update && apt-get install -y  libudunits2-dev libgdal-dev libgeos-dev libproj-dev libharfbuzz-dev libfribidi-dev")
install.packages("sf")
install.packages("textshaping")
install.packages("ragg")

# Install system dependencies of some other R packages that Voyager either imports or suggests:
system("apt-get install -y libfribidi-dev libcairo2-dev libmagick++-dev")

# Install anndata for cellatlas examples
install.packages("reticulate")
reticulate::install_miniconda()
install.packages("anndata")

# Install Voyager from Bioconductor:
install.packages("BiocManager")
BiocManager::install(version = "3.17", ask = FALSE, update = FALSE, Ncpus = 2)
BiocManager::install("scater")
system.time(
  BiocManager::install("Voyager", dependencies = TRUE, Ncpus = 2, update = FALSE)
)


packageVersion("Voyager")
```

# Introduction
The data in this vignette is shipped with the `cellatlas` repository. The count matrix and metadata are provided in the `cellatlas/examples` folder as an [`AnnData`](https://anndata-tutorials.readthedocs.io/en/latest/getting-started.html) object. We will begin by loading the object and converting it to a `SingleCellExperiment` object. 

```{r setup}
library(reticulate)
use_condaenv("r-reticulate")

library(anndata)
install_anndata()

library(stringr)
library(Matrix)
library(SpatialExperiment)
library(SpatialFeatureExperiment)
library(scater)
library(scuttle)
library(Voyager)
```

```{r dwnld}
# system("git clone https://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@github.com/cellatlas/cellatlas.git")

system("gunzip cellatlas/examples/rna-10xv3-nuclei/cellatlas_out/*gz")
ad <- read_h5ad("cellatlas/examples/rna-10xv3-nuclei/cellatlas_out/adata.h5ad")
```

```{r make-sce}
# Transpose X so that genes are on the rows
mat <- as(t(ad$X), "CsparseMatrix")
sce <- SingleCellExperiment(assays = list(counts=mat))
rowData(sce) <- ad$var
```

```{r}
is_mito <- str_detect(rowData(sce)$gene_name, regex("^mt-", ignore_case=TRUE))
sum(is_mito)
```

```{r}
sce <- addPerCellQCMetrics(sce, subsets = list(mito = is_mito))
names(colData(sce))
```

```{r}
plotColData(sce, "sum") +
    plotColData(sce, "detected") +
    plotColData(sce, "subsets_mito_percent")
```

```{r}
plotColDataBin2D(sce, x = "sum", y = "detected")
```

```{r}
plotColDataBin2D(sce, x = "sum", y = "subsets_mito_detected")
```

```{r subset-qc}
sce <- sce[, which(sce$subsets_mito_percent < 20)]
sce <- sce[rowSums(counts(sce)) > 0,]

sce
```